#app
server:
  port: 8888

#spring
spring:
  devtools:
    restart:
      exclude: static/**,public/**,templates/**
#      enabled: false

  # H2 DATABASE CONFIG
#  datasource:
#    schema: classpath:/db/schema-h2.sql
#    data: classpath:/db/data-h2.sql
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: sa
#    platform: h2
#    initialize: true
#    continue-on-error: true
#  h2:
#    console:
#      enabled: true
#      path: /console

  #mysql
  datasource:
    url: jdbc:mysql://116.62.134.242:3306/springboot?characterEncoding=utf8&useSSL=false
    username: springboot
    password: springboot
    driver-class-name: com.mysql.jdbc.Driver

  #thymeleaf
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html
#    注释的部分是Thymeleaf默认的配置，如有其它需求可以自行更改


#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.baomidou.springboot.entity
  global-config:
    id-type: 2
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level:
    com.baomidou.springboot: debug
